'use client';
import { useEffect, useState } from 'react';
import { FlaskConical, ImagePlus, ScanText, ShieldCheck } from 'lucide-react';
import { cohortStats, scenarioEconomics, type CohortAttempt, type ScenarioInput } from '@/lib/market';
import type { Card, Preferences } from '@/lib/types';
import { Empty, money, Notice, percent, Source, useStored } from './shared';

type Attempt = CohortAttempt & { originalGrade: string; finalOutcome: string; evidenceUrl: string; minimumGrade: string; notes: string; verification: string };
type Review = { id: string; issue: string; grader: string; grade: string; designation: string; cert: string; subgrades: Record<string, string>; concerns: string; imageAssessment: string; listing: string; verified: boolean; recordedAt: string; ocrText: string };
const concerns = ['Centering', 'Corners', 'Edges', 'Surface', 'Print / refractor lines', 'Scratches / dimples', 'Glare / slab scratches'];
export default function CardLab({ card, preferences }: { card?: Card; preferences: Preferences }) {
  const [photos, setPhotos] = useState<{ file: File; url: string }[]>([]);
  const [ocr, setOcr] = useState('');
  const [busy, setBusy] = useState(false);
  const [ocrStatus, setOcrStatus] = useState('');
  const [reviews, setReviews] = useStored<Review[]>('nce-reviews', []);
  const [attempts, setAttempts] = useStored<Attempt[]>('nce-attempts', []);
  const [method, setMethod] = useState('in-holder');
  const [issue, setIssue] = useState(card?.id || '');
  const [message, setMessage] = useState('');
  const stats = cohortStats(attempts, method, issue);
  useEffect(() => { return () => { photos.forEach(p => URL.revokeObjectURL(p.url)); }; }, [photos]);
  async function runOcr() {
    if (!photos.length) return;
    setBusy(true); setOcrStatus('Loading OCR engine…');
    let worker: Awaited<ReturnType<typeof import('tesseract.js').createWorker>> | undefined;
    try { const { createWorker } = await import('tesseract.js'); worker = await createWorker('eng', 1, { logger: m => setOcrStatus(`${m.status} · ${Math.round((m.progress || 0) * 100)}%`) }); const result = await worker.recognize(photos[0].file); setOcr(result.data.text); setOcrStatus(result.data.text.trim() ? `OCR complete · ${Math.round(result.data.confidence)}% engine confidence. Review every field manually.` : 'Unreadable image. Enter the label manually.'); } catch { setOcrStatus('OCR could not read this image or load its engine. Enter the label manually.'); } finally { await worker?.terminate(); setBusy(false); }
  }
  function saveReview(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault(); const f = new FormData(e.currentTarget);
    setReviews([...reviews, { id: crypto.randomUUID(), issue: String(f.get('issue')), grader: String(f.get('grader')), grade: String(f.get('grade')), designation: String(f.get('designation')), cert: String(f.get('cert')), subgrades: Object.fromEntries(['centering', 'corners', 'edges', 'surface'].map(k => [k, String(f.get(k) || '')])), concerns: f.getAll('concern').join(', '), imageAssessment: String(f.get('imageAssessment')), listing: String(f.get('listing')), verified: f.get('verified') === 'on', recordedAt: new Date().toISOString(), ocrText: ocr }]); setMessage('Manual review saved. Photos remain temporary and are not uploaded.');
  }
  function saveAttempt(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault(); const f = new FormData(e.currentTarget); const result = String(f.get('result')); if (result !== 'pending' && !f.get('completed')) { setMessage('A completed attempt needs its actual completion date.'); return; }
    setAttempts([...attempts, { id: crypto.randomUUID(), physicalCardId: String(f.get('physical')), cardId: issue, method, success: result === 'pending' ? null : result === 'success', completedAt: result === 'pending' ? null : String(f.get('completed')), originalGrade: String(f.get('original')), finalOutcome: result, minimumGrade: String(f.get('minimum')), evidenceUrl: String(f.get('evidence')), notes: String(f.get('notes')), verification: 'user-reported' }]); setMessage('Attempt recorded as user-reported evidence.'); e.currentTarget.reset();
  }
  return <>
    <div className="page-heading compact"><div><div className="eyebrow">OBSERVE. VERIFY. MODEL.</div><h1>Card Lab</h1><p>The current grade, a hypothetical PSA outcome, and the evidence are separate things.</p></div><span className="pill"><FlaskConical size={14} /> MANUAL EVIDENCE REVIEW</span></div>
    {message && <div className="success-notice" role="status">{message}</div>}
    <div className="two-column"><section className="panel padded"><div className="panel-heading"><h2>Slab photos & label review</h2><ImagePlus size={20} /></div><label className="upload-area">Front, back, and close-up photos<input type="file" accept="image/*" multiple onChange={e => { const files = Array.from(e.target.files || []).slice(0, 5); setPhotos(files.map(file => ({ file, url: URL.createObjectURL(file) }))); setOcr(''); setOcrStatus(''); }} /><span>Images stay in your browser. Review glare and slab damage separately.</span></label><div className="photo-grid">{photos.map(p => <img key={p.url} src={p.url} alt={`Manual inspection: ${p.file.name}`} />)}</div><button className="outline-btn" disabled={!photos.length || busy} onClick={runOcr}><ScanText size={16} />{busy ? 'Reading label…' : 'Run local OCR on first photo'}</button><p className="muted" role="status">{ocrStatus || 'OCR downloads an engine and language data; your photo is processed locally. Unreadable labels require manual entry.'}</p>{ocr && <label>Extracted text · unverified<textarea value={ocr} onChange={e => setOcr(e.target.value)} rows={5} /></label>}<Notice>No image-only grade prediction. Photos may hide surface damage; centering alone does not establish a PSA 10.</Notice></section>
    <section className="panel padded"><h2>Observed current grade</h2><form className="form-grid" onSubmit={saveReview}><label className="span-two">Exact card issue<input name="issue" defaultValue={card?.id || ''} placeholder="Year, set, parallel, card #, player" required /></label><label>Grader<select name="grader"><option>SGC</option><option>BGS</option><option>CGC</option><option>PSA</option><option>Raw</option></select></label><label>Observed card grade<input name="grade" required placeholder="9.5, 10, or ungraded" /></label><label>Designation / scale era<input name="designation" placeholder="MINT+, Gem Mint, Pristine, legacy…" /></label><label>Cert number<input name="cert" /></label><label className="span-two">Listing / evidence URL<input name="listing" type="url" /></label>{['centering', 'corners', 'edges', 'surface'].map(k => <label key={k}>Observed {k} subgrade<input name={k} placeholder="Leave blank if absent" /></label>)}<label className="span-two">Image assessment<select name="imageAssessment"><option>Insufficient to assess hidden defects</option><option>Readable label, visible card concerns only</option><option>Unreadable or conflicting label: review required</option></select></label><fieldset className="span-two"><legend>Visible concern or hypothesis · not official feedback</legend>{concerns.map(c => <label className="checkbox-label" key={c}><input name="concern" type="checkbox" value={c} />{c}</label>)}</fieldset><label className="checkbox-label span-two"><input name="verified" type="checkbox" />I checked the cert with the issuing grader manually</label><button className="primary-btn" type="submit">Save manual review</button></form><Source url="https://www.psacard.com/gradingstandards">PSA official standards</Source><p className="muted">A cert lookup does not authenticate the physical slab. Subgrades describe categories; they are not averaged into a PSA forecast.</p></section></div>
    <section className="panel padded"><div className="panel-heading"><div><h2>Paired physical-card outcomes</h2><p>Manually entered reports · same physical card · methods separated</p></div><ShieldCheck size={19} /></div><div className="form-grid"><label className="span-two">Exact issue ID for cohort<input value={issue} onChange={e => setIssue(e.target.value)} placeholder={card?.id || 'Exact canonical issue ID'} /></label><label>Submission method<select value={method} onChange={e => setMethod(e.target.value)}><option value="in-holder">In-holder crossover</option><option value="crack-and-submit">Crack-and-submit</option><option value="raw-first">Raw-first submission</option></select></label></div><div className="mini-stats"><div><small>All attempts</small><b>{stats.attempts}</b></div><div><small>Independent completed cards</small><b>{stats.completed}</b></div><div><small>Pending attempts</small><b>{stats.pending}</b></div></div><h3>Insufficient crossover evidence</h3><p>{stats.completed ? `${stats.successes} / ${stats.completed} user-reported threshold successes · ${percent(stats.rate)} · 95% Wilson interval ${percent(stats.interval?.low)}–${percent(stats.interval?.high)}.` : 'No eligible paired outcomes recorded for this exact issue and method.'}</p><Notice>Only the first eligible completed attempt per physical card counts. Fewer than 30 independent cards is exploratory. User-reported records are not verified forecasts; reporting bias remains. An unsuccessful minimum-10 crossover is censored and does not establish PSA 9.</Notice><details className="details"><summary>Record an attempt, including a failure or pending submission</summary><form className="form-grid" onSubmit={saveAttempt}><label>Physical-card ID<input name="physical" required placeholder="One stable ID for this physical card" /></label><label>Original grader / grade / scale<input name="original" required placeholder="SGC 9.5 MINT+" /></label><label>Minimum requested grade<input name="minimum" required defaultValue="PSA 10" /></label><label>Threshold outcome<select name="result"><option value="pending">Pending</option><option value="success">Met requested threshold</option><option value="failure">Failed / rejected / no-grade</option></select></label><label>Completed date<input name="completed" type="date" /></label><label>Before / after evidence URL<input name="evidence" type="url" required /></label><label className="span-two">Notes and actual grade if known<textarea name="notes" rows={2} /></label><button className="primary-btn" disabled={!issue}>Record attempt</button></form></details><details className="details"><summary>Show attempts and original evidence</summary><pre>{JSON.stringify(attempts.filter(a => a.cardId === issue && a.method === method), null, 2)}</pre></details></section>
    <Economics preferences={preferences} />
    <details className="panel padded"><summary>Saved manual slab reviews ({reviews.length})</summary><pre>{JSON.stringify(reviews, null, 2)}</pre></details>
  </>;
}

const economicsFields: [keyof ScenarioInput, string][] = [
  ['entry', 'Item entry price'], ['inboundShipping', 'Inbound postage'], ['buyerFees', 'Buyer charges (USD)'], ['taxRate', 'Tax fraction (0–1)'],
  ['gradingFee', 'Grading / crossover fee'], ['gradingShipping', 'Round-trip postage / insurance'], ['packaging', 'Packaging'], ['successExtra', 'Success-specific upcharge'], ['failureExtra', 'Failure-specific extra cost'],
  ['exitSuccess', 'Success resale item price'], ['exitFailure', 'Failure / retained-slab item value'], ['sellingFeeRate', 'Selling fee fraction (0–1)'], ['sellingFixed', 'Fixed selling fee'], ['outboundShipping', 'Outbound shipping'], ['successProbability', 'Hypothetical success probability (0–1)'], ['targetRoi', 'Target ROI fraction (0–1+)'], ['maxLoss', 'Maximum scenario loss (USD)'],
];
function Economics({ preferences }: { preferences: Preferences }) {
  const [result, setResult] = useState<ReturnType<typeof scenarioEconomics> | null>(null);
  const [error, setError] = useState('');
  function calculate(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const input = Object.fromEntries(economicsFields.map(([key]) => [key, Number(f.get(key))])) as ScenarioInput; try { setResult(scenarioEconomics(input)); setError(''); } catch (e) { setResult(null); setError(e instanceof Error ? e.message : 'Invalid assumptions.'); } }
  return <section className="panel padded"><div className="panel-heading"><div><h2>Conditional strategy economics</h2><p>Editable two-outcome scenario. Enter fees from a dated, verified quote.</p></div><span className="pill amber">ASSUMPTIONS, NOT FORECASTS</span></div><Notice>For an in-holder failure, enter the original slab’s retained resale value and charge its unsuccessful submission costs. Crack-and-submit requires lower-grade, no-grade, and damage scenarios beyond this two-outcome calculator. It is never the default.</Notice><form className="form-grid economics-form" onSubmit={calculate}>{economicsFields.map(([key, label]) => <label key={key}>{label}<input name={key} type="number" step="0.01" min="0" max={['taxRate', 'sellingFeeRate', 'successProbability'].includes(key) ? '1' : undefined} required defaultValue={key === 'targetRoi' ? preferences.targetRoi ?? '' : key === 'maxLoss' ? preferences.maxLoss ?? '' : ''} placeholder="Enter your assumption" /></label>)}<button className="primary-btn" type="submit">Calculate scenario</button></form>{error && <p role="alert" className="errors">{error}</p>}{result && <div className="scenario-result"><div className="stat-grid"><div><small>Expected profit</small><b>{money(result.expectedProfit)}</b></div><div><small>Expected cash ROI</small><b>{percent(result.roi)}</b></div><div><small>Worst committed cash</small><b>{money(result.worstCash)}</b></div><div><small>Conditional max item entry</small><b>{money(result.maximumEntry)}</b></div></div><p>Break-even success probability: <b>{percent(result.breakEvenProbability)}</b> · {result.breakEvenStatus}. Thresholds outside 0–100% are shown without clamping.</p><p>Common cash cost {money(result.commonCost)} · net success proceeds {money(result.netSuccess)} · net failure proceeds {money(result.netFailure)} · worst modeled profit {money(result.worstProfit)}.</p><p className="mono">Expected profit = p × (net success − success extra) + (1 − p) × (net failure − failure extra) − common cost</p><Notice>Tax applies to item entry; selling percentage applies to item resale. Adapt the inputs for your marketplace’s actual fee bases. An unsold-at-horizon case has zero realized sale proceeds and retains inventory risk. Turnaround and liquidity are not verified. This calculation does not issue a personalized position size.</Notice></div>}</section>;
}
