'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, Bookmark, Check, ChevronRight, CircleHelp, FileText, FlaskConical, Layers3, Search, Settings2, ShieldCheck, SlidersHorizontal, TrendingUp, Upload, Wallet, Zap } from 'lucide-react';
import type { Card, NFLData, OwnedCard, Player } from '@/lib/types';
import { emptyData, emptyPreferences } from '@/lib/types';
import type { Population, SoldSale } from '@/lib/market';
import { saleSummary } from '@/lib/market';
import { date, download, Empty, exportPrivateBackup, money, Notice, number, percent, Source, UsageChart, useStored } from './shared';
import SettingsView from './SettingsView';
import CardLab from './CardLab';
import CardPricing from './CardPricing';
import type { ListingSnapshot } from '@/lib/ebay';

type View = 'opportunities' | 'player' | 'lab' | 'watchlist' | 'reports' | 'settings';
const base = process.env.NEXT_PUBLIC_BASE_PATH || '';
const navigation = [
  { id: 'opportunities', label: 'Opportunities', icon: TrendingUp },
  { id: 'watchlist', label: 'Watchlist', icon: Bookmark },
  { id: 'lab', label: 'Card Lab', icon: FlaskConical },
  { id: 'reports', label: 'Weekly reports', icon: FileText },
  { id: 'settings', label: 'Settings & data', icon: Settings2 },
] as const;
const fallbackWilson: Player = { id: 'michael-wilson', name: 'Michael Wilson', team: 'ARI', position: 'WR', score: 50, trend: 0, latest: { week: 0 }, baseline: {}, history: [], reasons: ['No current source sample available.'], sourceUrl: 'https://github.com/nflverse/nflverse-data/releases' };

export default function ResearchApp() {
  const [view, setView] = useState<View>('opportunities');
  const [data, setData] = useState<NFLData>(emptyData);
  const [catalog, setCatalog] = useState<Card[]>([]);
  const [listingSnapshot, setListingSnapshot] = useState<ListingSnapshot>({ status: 'unconfigured', updatedAt: null, listings: [] });
  const [loadError, setLoadError] = useState('');
  const [selected, setSelected] = useState<Player>(fallbackWilson);
  const [query, setQuery] = useState('');
  const [position, setPosition] = useState('ALL');
  const [populations, setPopulations] = useStored<Population[]>('nce-populations', []);
  const [sales, setSales] = useStored<SoldSale[]>('nce-sales', []);
  const [watchlist, setWatchlist] = useStored<string[]>('nce-watchlist', ['Michael Wilson']);
  const [owned, setOwned] = useStored<OwnedCard[]>('nce-owned', []);
  const [preferences, setPreferences] = useStored('nce-preferences', emptyPreferences);
  const [limit, setLimit] = useState(40);
  useEffect(() => {
    const hash = location.hash.slice(1);
    if (navigation.some(x => x.id === hash)) setView(hash as View);
    else if (hash === 'player' || hash.startsWith('player=')) { const name = new URLSearchParams(hash).get('player') || 'Michael Wilson'; setView('player'); setSelected({ ...fallbackWilson, id: name, name, team: '—', position: '—' }); }
    fetch(`${base}/data/nfl.json`).then(r => { if (!r.ok) throw Error('Football snapshot unavailable.'); return r.json(); }).then((next: NFLData) => { setData(next); if (location.hash.startsWith('#player')) { const name = new URLSearchParams(location.hash.slice(1)).get('player') || 'Michael Wilson'; setSelected(next.players.find(p => p.name === name) || { ...fallbackWilson, id: name, name, team: '—', position: '—' }); } }).catch(e => setLoadError(e.message));
    fetch(`${base}/data/catalog.json`).then(r => r.json()).then(setCatalog).catch(() => {});
    fetch(`${base}/data/listings.json`).then(r => { if (!r.ok) throw Error('Listing quotes unavailable.'); return r.json(); }).then(setListingSnapshot).catch(() => setListingSnapshot({ status: 'error', updatedAt: null, listings: [] }));
  }, []);
  const go = (next: View, playerName?: string) => { setView(next); location.hash = next === 'player' && playerName ? `player=${encodeURIComponent(playerName)}` : next; window.scrollTo({ top: 0, behavior: 'instant' }); };
  const openPlayer = (player: Player) => { setSelected(player); go('player', player.name); };
  const toggleWatch = (name: string) => setWatchlist(watchlist.includes(name) ? watchlist.filter(x => x !== name) : [...watchlist, name]);
  const players = useMemo(() => data.players.filter(p => (position === 'ALL' || p.position === position) && `${p.name} ${p.team} ${p.position}`.toLowerCase().includes(query.toLowerCase())), [data.players, query, position]);
  const rising = data.players.filter(p => p.score > 55 && p.history.length >= 2).length;
  const currentCards = catalog.filter(c => c.player === selected.name);
  const [cardId, setCardId] = useState('');
  const card = currentCards.find(c => c.id === cardId) || currentCards[0];
  const playerPop = populations.filter(p => p.player.toLowerCase() === selected.name.toLowerCase());
  const exactPop = card ? playerPop.find(p => Number(p.year) === card.year && p.cardNumber === card.cardNumber && p.set.replace(/^Panini /i, '').toLowerCase() === card.set.replace(/^Panini /i, '').toLowerCase() && /^silver(?: prizm)?$/i.test(p.parallel)) : undefined;
  const needsSettings = Object.values(preferences).some(x => x === null || x === '');
  const report = data.reports[data.reports.length - 1];
  const fresh = data.updatedAt && Date.now() - new Date(data.updatedAt).getTime() < 96 * 3600000;

  return <div className="app-shell">
    <aside className="sidebar">
      <a className="brand" href="#opportunities" onClick={() => go('opportunities')} aria-label="NFL Card Edge home"><span className="brand-mark"><Layers3 size={23} /></span><span>NFL CARD<span className="brand-edge">EDGE<span className="brand-dot">.</span></span></span></a>
      <div className="nav-label">YOUR RESEARCH DESK</div>
      <nav>{navigation.map(item => <button key={item.id} aria-label={item.label} className={`nav-item ${view === item.id || view === 'player' && item.id === 'opportunities' ? 'active' : ''}`} onClick={() => go(item.id)} aria-current={view === item.id ? 'page' : undefined}><item.icon size={18} /><span>{item.label}</span>{item.id === 'watchlist' && <span className="nav-count">{watchlist.length}</span>}</button>)}<a className="nav-item" href={`${base}/research/2026-10-06/`}><FileText size={18} /><span>Investment deep dive</span></a></nav>
      <div className="sidebar-bottom"><div className="cloud-status"><span className="live-dot" /> GITHUB CLOUD</div><p>Your research stays online.<br />Your private imports stay here.</p><Source url="https://github.com/rdsciv/nfl-card-edge">View source & cloud jobs</Source><div className="profile"><span>RC</span><div><b>Personal research</b><small>Paper-trading workspace</small></div><ShieldCheck size={16} /></div></div>
    </aside>
    <div className="main-shell">
      <header className="topbar"><div className="breadcrumb">Research desk <ChevronRight size={14} /><b>{view === 'player' ? selected.name : navigation.find(x => x.id === view)?.label}</b></div><div className="topbar-right"><span className="mode"><span /> PAPER TRADING</span><button className="icon-btn" aria-label="Data health" onClick={() => go('settings')}><Activity size={19} /></button></div></header>
      <main id="main">
      {view === 'opportunities' && <>
        <div className="page-heading"><div><div className="eyebrow">FOOTBALL SIGNALS. CARD EVIDENCE.</div><h1>Find the opportunity.<br />Then find the <em>edge.</em></h1><p>Track changing roles. Research exact cards. Make evidence-led decisions.</p></div><button className="primary-btn" onClick={() => go('settings')}><Upload size={16} /> Import card data</button></div>
        <div className="season-line"><span className={`pill ${data.status === 'live' && fresh ? 'green' : 'amber'}`}><span className="tiny-dot" />{data.status === 'live' && fresh ? 'NFL DATA CONNECTED' : 'CHECK DATA COVERAGE'}</span><span>{data.season ?? 'Season unresolved'}{data.completedWeek != null ? ` season · completed week ${data.completedWeek}` : ''}{data.partialWeek ? ' · next week partial' : ''}</span><span className="last-refresh">Updated {date(data.updatedAt)}</span></div>
        {(loadError || data.status !== 'live' || !fresh) && <Notice>{loadError || 'Some inputs are unavailable or stale. Rankings use published data only.'} Review <button className="text-btn" onClick={() => go('settings')}>data health</button> before acting.</Notice>}
        <div className="stat-grid"><Stat label="Players covered" value={data.coverage.players.toLocaleString()} foot="QB · RB · WR · TE" icon={<Activity size={19} />} /><Stat label="Usage gaining ground" value={String(rising)} foot="Score above 55 · 2+ games" icon={<TrendingUp size={19} />} /><Stat label="On your watchlist" value={String(watchlist.length).padStart(2, '0')} foot="Saved in this browser" icon={<Bookmark size={19} />} /><Stat label="Verified sold feed" value="Not connected" foot="Manual CSV imports available" icon={<Layers3 size={19} />} /></div>
        <div className="dashboard-grid"><section className="panel opportunities-panel"><div className="panel-heading"><div><h2>Opportunity board <span className="count-tag">{players.length}</span></h2><p>Football momentum first. Market value needs its own evidence.</p></div><SlidersHorizontal size={18} /></div>
          <div className="table-tools"><div className="search-input"><Search size={17} /><input aria-label="Search players" value={query} onChange={e => { setQuery(e.target.value); setLimit(40); }} placeholder="Search player or team…" /></div><div className="position-tabs">{['ALL', 'QB', 'RB', 'WR', 'TE'].map(p => <button key={p} className={position === p ? 'selected' : ''} onClick={() => { setPosition(p); setLimit(40); }}>{p === 'ALL' ? 'All' : p}</button>)}</div></div>
          {players.length ? <div className="table-scroll"><table className="player-table"><thead><tr><th>PLAYER</th><th>EDGE SCORE <CircleHelp size={12} /></th><th>LATEST USAGE</th><th>ROLE SIGNAL</th><th>STRATEGY</th><th><span className="sr-only">Watch</span></th></tr></thead><tbody>{players.slice(0, limit).map((p, i) => <tr key={p.id}><td><button className="player-cell" onClick={() => openPlayer(p)}><span className={`player-initial team-${p.team}`}>{p.name.split(' ').map(x => x[0]).slice(0, 2).join('')}</span><span><b>{p.name}</b><small>{p.team} <span>·</span> {p.position}</small></span></button></td><td><div className="score-cell"><b>{number(p.score, 0)}</b><div className="score-track"><span style={{ width: `${p.score}%` }} /></div></div></td><td><b>{p.position === 'QB' ? number(p.latest.attempts, 0) : p.position === 'RB' ? number(p.latest.touches, 0) : number(p.latest.targets, 0)}</b><small className="cell-small">{p.position === 'QB' ? 'attempts' : p.position === 'RB' ? 'touches' : 'targets'} · W{p.latest.week || '—'}</small></td><td><span className={`trend ${p.trend > 0 ? 'positive' : ''}`}>{p.trend > 0 ? <ArrowUpRight size={14} /> : p.trend < 0 ? <ArrowDown size={14} /> : <span>—</span>}{number(p.trend, 1)} pts</span><small className="cell-small">usage score change</small></td><td><span className="watch-pill">WATCH</span></td><td><button className={`icon-btn bookmark-btn ${watchlist.includes(p.name) ? 'saved' : ''}`} aria-label={`${watchlist.includes(p.name) ? 'Remove' : 'Watch'} ${p.name}`} onClick={() => toggleWatch(p.name)}><Bookmark size={17} fill={watchlist.includes(p.name) ? 'currentColor' : 'none'} /></button></td></tr>)}</tbody></table>{players.length > limit && <button className="load-more" onClick={() => setLimit(limit + 40)}>Show 40 more players</button>}</div> : <Empty title={query ? 'No matching players' : 'Waiting for football data'} text={query ? 'Try a name, team abbreviation, or another position.' : 'The cloud worker publishes a snapshot when the schedule and player statistics are available.'} />}
          <div className="panel-footer"><span><span className="tiny-dot" /> nflverse · published weekly statistics</span><button className="text-btn" onClick={() => go('settings')}>Score methodology <ArrowRight size={13} /></button></div>
        </section><div className="right-column"><section className="panel spotlight"><div className="eyebrow"><Zap size={13} /> START YOUR RESEARCH</div><div className="spotlight-number">01 <span>/ WATCHLIST</span></div><h2>Michael Wilson</h2><p className="spotlight-meta">ARIZONA · WIDE RECEIVER</p><div className="card-identity"><Layers3 size={25} /><div><b>2023 Panini Prizm</b><span>Silver rookie · #{catalog.find(c => c.player === 'Michael Wilson')?.cardNumber || '303 · review identity'}</span></div></div><p>Separate a changing role from a one-game spike. Then compare exact Silver rookie comps.</p><button className="dark-btn" onClick={() => openPlayer(data.players.find(p => p.name === 'Michael Wilson') || fallbackWilson)}>Research Michael Wilson <ArrowUpRight size={17} /></button></section>
          <section className="panel evidence-panel"><div className="section-icon"><ShieldCheck size={19} /></div><h3>Good signals need good evidence.</h3><p>Population gem rate describes graded cards. It does not predict your raw card’s outcome.</p><div className="evidence-row"><Check size={14} /> Exact card identity</div><div className="evidence-row"><Check size={14} /> Realized sales, separate from asks</div><div className="evidence-row"><Check size={14} /> Crossover attempts, including failures</div><button className="text-btn" onClick={() => go('lab')}>Explore Card Lab <ArrowRight size={14} /></button></section>
        </div></div>
        <div className="disclaimer-line"><ShieldCheck size={14} /> Research, not guaranteed returns. Watch signals become trade scenarios only when evidence and settings support them.</div>
      </>}
      {view === 'player' && <>
        <button className="back-btn" onClick={() => go('opportunities')}><ArrowLeft size={15} /> Opportunity board</button><div className="page-heading compact"><div><div className="eyebrow">{selected.team} · {selected.position} · PLAYER RESEARCH</div><h1>{selected.name}</h1><p>Football opportunity and card economics, with the evidence kept visible.</p></div><button className="primary-btn" onClick={() => toggleWatch(selected.name)}><Bookmark size={16} /> {watchlist.includes(selected.name) ? 'Remove from watchlist' : 'Add to watchlist'}</button></div>
        <CardPricing key={`${selected.name}-${card?.id || 'search'}`} player={selected.name} card={card} snapshot={listingSnapshot} sales={sales} />
        <div className="two-column"><section className="panel padded"><div className="panel-heading"><h2>Role & opportunity</h2><span className="pill green">SCORE {number(selected.score, 0)}</span></div><UsageChart history={selected.history} field={selected.position === 'QB' ? 'attempts' : selected.position === 'RB' ? 'carries' : 'targets'} /><div className="mini-stats"><div><small>Targets</small><b>{number(selected.latest.targets, 0)}</b></div><div><small>Team target share</small><b>{percent(selected.latest.targetShare)}</b></div><div><small>Offensive snap share</small><b>{percent(selected.latest.snapShare)}</b></div></div><ul className="reasons">{selected.reasons.map((r, i) => <li key={i}>{r}</li>)}</ul><Source url={selected.sourceUrl}>nflverse statistics</Source><Notice>Routes and confirmed role catalysts require a current supported feed. A usage change alone does not establish its cause.</Notice></section>
          <section className="panel padded"><div className="panel-heading"><h2>Exact card identity</h2><span className="pill">{card?.verified ? 'CHECKLIST VERIFIED' : 'REVIEW NEEDED'}</span></div>{card ? <><div className="research-card"><Layers3 size={38} /><div className="eyebrow">{card.year} · {card.manufacturer}</div><h3>{card.set} {card.parallel}</h3><p>#{card.cardNumber} · Rookie · No autograph · No variation</p></div>{currentCards.length > 1 && <label>Card issue<select value={card.id} onChange={e => setCardId(e.target.value)}>{currentCards.map(c => <option key={c.id} value={c.id}>{c.year} {c.set} {c.parallel} #{c.cardNumber}</option>)}</select></label>}<p className="muted">Base, collegiate, variation, autograph, and other parallels are excluded from this issue.</p><Source url={card.sourceUrl}>View identity evidence</Source><p className="mono small-text">Import card_id: {card.id}</p></> : <Empty title="Card identity needs review" text="No verified Silver rookie checklist entry has been added for this player. Do not pool other cards into its comps." />}<button className="outline-btn full-width" onClick={() => go('lab')}>Open Card Lab <ArrowUpRight size={15} /></button></section></div>
        <section className="panel"><div className="panel-heading"><div><h2>Exact-issue sold comps</h2><p>USD only · item-only medians · minimum 5 comps · user-reported records remain labeled</p></div><button className="outline-btn" onClick={() => go('settings')}>Import sales <Upload size={14} /></button></div>{card && sales.some(s => s.cardId === card.id) ? <div className="table-scroll"><table><thead><tr><th>GRADE BUCKET</th><th>7 DAYS</th><th>30 DAYS</th><th>90 DAYS</th><th>30D SAMPLE</th><th>COVERAGE</th></tr></thead><tbody>{[['RAW', 'Raw'], ['PSA', '9'], ['PSA', '10'], ['SGC', '9.5'], ['BGS', '9.5'], ['CGC', '10']].map(([g, grade]) => { const summary = saleSummary(sales.filter(s => s.currency === 'USD'), card.id, g, grade, 30); return <tr key={g + grade}><td><b>{g} {grade}</b>{summary.labelCoverage.designations.length === 1 && <small className="cell-small">{summary.labelCoverage.designations[0]}</small>}</td>{[7, 30, 90].map(days => <td key={days}>{money(saleSummary(sales.filter(s => s.currency === 'USD'), card.id, g, grade, days).median)}</td>)}<td>{summary.count}</td><td><span className={`pill ${summary.actionable ? 'green' : 'amber'}`}>{summary.labelIssue ? 'LABEL REVIEW NEEDED' : summary.actionable ? 'ENOUGH COMPS' : 'THIN SAMPLE'}</span></td></tr>; })}</tbody></table></div> : <Empty title="No verified sold comps" text="No automatic sold-price feed is connected. Import confirmed or clearly labeled user-reported exact-card sales. Current asks and unknown Best Offers are not sale prices." />}<details className="details"><summary>Show imported individual comps & provenance</summary><div className="table-scroll"><table><thead><tr><th>SALE DATE</th><th>TITLE</th><th>GRADE</th><th>ITEM</th><th>SHIPPING</th><th>STATUS</th></tr></thead><tbody>{sales.filter(s => s.cardId === card?.id).map(s => <tr key={s.sourceId}><td>{s.saleDate}</td><td><Source url={s.sourceUrl}>{s.title}</Source></td><td>{s.grader} {s.grade}<small className="cell-small">{s.designation || "Designation not supplied"} {s.scaleEra || ""}</small></td><td>{s.currency} {s.itemPrice}</td><td>{s.shipping == null ? 'Unknown' : s.shipping}</td><td>{s.verification}</td></tr>)}</tbody></table></div></details></section>
        <div className="two-column"><section className="panel padded"><div className="panel-heading"><h2>Population gem rate</h2><span className="pill">MANUAL SOURCE</span></div>{exactPop ? <><div className="gem-number">{percent(exactPop.rate)}</div><p><b>{exactPop.gems.toLocaleString()}</b> PSA 10 / <b>{exactPop.total.toLocaleString()}</b> reported population</p><Notice>{exactPop.denominatorVerified ? 'Explicit numeric-grade denominator supplied by the importer.' : 'Export denominator is unverified: explicit numeric grade buckets are not supplied.'} Snapshot date: {exactPop.snapshotDate || 'unknown'}.</Notice><Source url={exactPop.sourceUrl}>Population source</Source><p className="muted">Submission selection and resubmissions affect this statistic. It is not a raw grading probability.</p></> : <Empty title="Population data unavailable" text="Import an exact-issue population snapshot. Broader set rates are not substituted." />}</section><section className="panel padded"><div className="panel-heading"><h2>Strategy comparison</h2><span className="watch-pill">WATCH</span></div><p>{needsSettings ? 'Complete your investor settings before personalized position sizing.' : 'Investor settings saved. Position sizes still require supported exact-card price and outcome evidence.'}</p><div className="strategy-list">{['Raw → resell', 'Raw → grade', 'Buy PSA slab', 'Resell other slab intact', 'In-holder PSA crossover', 'Hold / sell existing card'].map(s => <div key={s}><span>{s}</span><b>Evidence needed</b></div>)}</div><button className="outline-btn full-width" onClick={() => go('lab')}>Model conditional economics <ArrowRight size={14} /></button><p className="muted">No position size or maximum bid is personalized until settings, price coverage, and grading evidence are sufficient.</p></section></div>
      </>}
      {view === 'lab' && <CardLab card={card} preferences={preferences} />}
      {view === 'watchlist' && <>
        <div className="page-heading compact"><div><div className="eyebrow">YOUR PERSONAL RESEARCH</div><h1>Watchlist & portfolio</h1><p>Follow the thesis. Record the outcome. Keep the misses, too.</p></div><button className="outline-btn" onClick={exportPrivateBackup}>Export private backup</button></div><Notice>Saved only in this browser. Records are not uploaded to GitHub or shared across devices. Export a backup before clearing browser storage.</Notice><section className="panel padded"><h2>Watched players</h2><div className="watch-grid">{watchlist.map(name => <div className="watch-card" key={name}><div className="watch-card-head"><Bookmark size={18} /><button className="text-btn" aria-label={`Remove ${name} from watchlist`} onClick={() => toggleWatch(name)}>Remove</button></div><h3>{name}</h3><p>{data.players.find(p => p.name === name)?.team || 'Card research'} · Watch</p><button className="outline-btn full-width" onClick={() => openPlayer(data.players.find(p => p.name === name) || { ...fallbackWilson, id: name, name })}>Research {name} <ArrowRight size={14} /></button></div>)}</div>{!watchlist.length && <Empty title="Your watchlist is empty" text="Bookmark a player from the opportunity board." />}</section><Portfolio owned={owned} setOwned={setOwned} /></>}
      {view === 'reports' && <>
        <div className="page-heading compact"><div><div className="eyebrow">DATED FOOTBALL SNAPSHOTS</div><h1>Weekly reports</h1><p>Preserved snapshots from the cloud pipeline. No look-ahead rewrites.</p></div><Source url="https://github.com/rdsciv/nfl-card-edge/actions">Run now in GitHub</Source></div><Notice>Tuesday 9:15 AM and Friday 4:15 PM America/Chicago. GitHub may delay scheduled execution. Saturday catch-up rechecks late inputs. Sold-price updates are unavailable.</Notice>{data.reports.length ? [...data.reports].reverse().map(r => <section key={r.id} className="panel padded report-card"><div className="panel-heading"><div><div className="eyebrow">{r.kind} · {r.status}</div><h2>{r.season} season · Week {r.week}</h2><p>{date(r.date)} · {r.playerCount} players</p></div><span className="pill">{r.id}</span></div><div className="report-leaders">{r.leaders.slice(0, 5).map((p, i) => <button key={p.id} onClick={() => openPlayer(data.players.find(x => x.id === p.id) || { ...fallbackWilson, ...p })}><span>0{i + 1}</span><b>{p.name}</b><em>{number(p.score, 0)}</em></button>)}</div><details className="details"><summary>View this immutable report</summary><pre>{JSON.stringify(r, null, 2)}</pre></details><button className="text-btn" onClick={() => download(`${r.id}.json`, r)}>Download report JSON <ArrowDown size={14} /></button></section>) : <Empty title="No report published yet" text="The cloud pipeline publishes after validation. A failed source leaves the last good snapshot intact." />}</>}
      {view === 'settings' && <SettingsView data={data} listingSnapshot={listingSnapshot} populations={populations} setPopulations={setPopulations} sales={sales} setSales={setSales} preferences={preferences} setPreferences={setPreferences} />}
      <footer className="footer"><span>NFL CARD EDGE <span>·</span> EVIDENCE OVER HYPE</span><span>Public research · private browser workspace</span></footer>
      </main>
    </div>
  </div>;
}

function Stat({ label, value, foot, icon }: { label: string; value: string; foot: string; icon: React.ReactNode }) { return <div className="stat-card"><div><span>{label}</span>{icon}</div><b className={value.length > 10 ? 'long-stat' : ''}>{value}</b><small>{foot}</small></div>; }

function Portfolio({ owned, setOwned }: { owned: OwnedCard[]; setOwned: (cards: OwnedCard[]) => void }) {
  const [error, setError] = useState('');
  function save(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); const cost = Number(form.get('cost')); const proceedsText = String(form.get('proceeds') || ''); const proceeds = proceedsText ? Number(proceedsText) : null; if (cost < 0 || !Number.isFinite(cost) || proceeds != null && (!Number.isFinite(proceeds) || proceeds < 0)) { setError('Costs and proceeds must be nonnegative amounts.'); return; } setOwned([...owned, { id: crypto.randomUUID(), player: String(form.get('player')), card: String(form.get('card')), grade: String(form.get('grade')), cost, proceeds, status: String(form.get('status')) }]); setError(''); e.currentTarget.reset(); }
  return <section className="panel padded"><div className="panel-heading"><h2>Owned cards & realized outcomes</h2><Wallet size={20} /></div><form className="form-grid" onSubmit={save}><label>Player<input name="player" required /></label><label>Exact card issue<input name="card" required placeholder="Year · set · parallel · #" /></label><label>Current grade<input name="grade" required placeholder="Grader · grade · designation" /></label><label>All-in acquisition cost<input name="cost" type="number" step="0.01" min="0" required /></label><label>Net realized proceeds<input name="proceeds" type="number" step="0.01" min="0" placeholder="Leave blank if unsold" /></label><label>Status<select name="status"><option>Owned</option><option>Submitted</option><option>Crossover rejected</option><option>Returned graded</option><option>Sold</option></select></label><button className="primary-btn" type="submit">Add portfolio record</button>{error && <p role="alert">{error}</p>}</form>{owned.length ? <div className="table-scroll"><table><thead><tr><th>PLAYER / CARD</th><th>GRADE</th><th>STATUS</th><th>COST</th><th>PROCEEDS</th><th>REALIZED PROFIT</th></tr></thead><tbody>{owned.map(c => <tr key={c.id}><td><b>{c.player}</b><small className="cell-small">{c.card}</small></td><td>{c.grade}</td><td>{c.status}</td><td>{money(c.cost)}</td><td>{money(c.proceeds)}</td><td>{c.proceeds == null ? 'Unrealized' : money(c.proceeds - c.cost)}</td></tr>)}</tbody></table></div> : <Empty title="No owned cards yet" text="Add actual costs, submission status, and net proceeds to evaluate realized results." />}</section>;
}
